Weights:
  eventWeight:
    - "genWeight"
    - "puWeight"
    - "lep.electronIDWeight"
    - "lbar.electronIDWeight"
    - "lep.muonIDWeight"
    - "lbar.muonIDWeight"
    - "lep.muonIsoWeight"
    - "lbar.muonIsoWeight"
  trueLevelWeight:
    - "genWeight"