Data:
  2024:
    run2024C_EGamma:
      - /EGamma0/Run2024C-MINIv6NANOv15-v1/NANOAOD
      - /EGamma1/Run2024C-MINIv6NANOv15-v1/NANOAOD
    run2024C_Muon:
      - /Muon0/Run2024C-MINIv6NANOv15-v1/NANOAOD
      - /Muon1/Run2024C-MINIv6NANOv15-v1/NANOAOD
    run2024C_MuonEG:
      - /MuonEG/Run2024C-MINIv6NANOv15-v1/NANOAOD
    run2024C_Tau:
      - /Tau/Run2024C-MINIv6NANOv15-v1/NANOAOD
    run2024D_EGamma:
      - /EGamma0/Run2024D-MINIv6NANOv15-v1/NANOAOD
      - /EGamma1/Run2024D-MINIv6NANOv15-v1/NANOAOD
    run2024D_Muon:
      - /Muon0/Run2024D-MINIv6NANOv15-v1/NANOAOD
      - /Muon1/Run2024D-MINIv6NANOv15-v1/NANOAOD
    run2024D_MuonEG:
      - /MuonEG/Run2024D-MINIv6NANOv15-v1/NANOAOD
    run2024D_Tau:
      - /Tau/Run2024D-MINIv6NANOv15-v1/NANOAOD
    run2024E_EGamma:
      - /EGamma0/Run2024E-MINIv6NANOv15-v1/NANOAOD
      - /EGamma1/Run2024E-MINIv6NANOv15-v1/NANOAOD
    run2024E_Muon:
      - /Muon0/Run2024E-MINIv6NANOv15-v1/NANOAOD
      - /Muon1/Run2024E-MINIv6NANOv15-v1/NANOAOD
    run2024E_MuonEG:
      - /MuonEG/Run2024E-MINIv6NANOv15-v1/NANOAOD
    run2024E_Tau:
      - /Tau/Run2024E-MINIv6NANOv15-v1/NANOAOD
    run2024F_EGamma:
      - /EGamma0/Run2024F-MINIv6NANOv15-v1/NANOAOD
      - /EGamma1/Run2024F-MINIv6NANOv15-v1/NANOAOD
    run2024F_Muon:
      - /Muon0/Run2024F-MINIv6NANOv15-v1/NANOAOD
      - /Muon1/Run2024F-MINIv6NANOv15-v1/NANOAOD
    run2024F_MuonEG:
      - /MuonEG/Run2024F-MINIv6NANOv15-v2/NANOAOD
    run2024F_Tau:
      - /Tau/Run2024F-MINIv6NANOv15-v1/NANOAOD
    run2024G_EGamma:
      - /EGamma0/Run2024G-MINIv6NANOv15-v2/NANOAOD
      - /EGamma1/Run2024G-MINIv6NANOv15-v2/NANOAOD
    run2024G_Muon:
      - /Muon0/Run2024G-MINIv6NANOv15-v1/NANOAOD
      - /Muon1/Run2024G-MINIv6NANOv15-v2/NANOAOD
    run2024G_MuonEG:
      - /MuonEG/Run2024G-MINIv6NANOv15-v3/NANOAOD
    run2024G_Tau:
      - /Tau/Run2024G-MINIv6NANOv15-v1/NANOAOD
    run2024H_EGamma:
      - /EGamma0/Run2024H-MINIv6NANOv15-v2/NANOAOD
      - /EGamma1/Run2024H-MINIv6NANOv15-v1/NANOAOD
    run2024H_Muon:
      - /Muon0/Run2024H-MINIv6NANOv15-v1/NANOAOD
      - /Muon1/Run2024H-MINIv6NANOv15-v2/NANOAOD
    run2024H_MuonEG:
      - /MuonEG/Run2024H-MINIv6NANOv15-v2/NANOAOD
    run2024H_Tau:
      - /Tau/Run2024H-MINIv6NANOv15-v1/NANOAOD
    run2024I_EGamma:
      - /EGamma0/Run2024I-MINIv6NANOv15-v1/NANOAOD
      - /EGamma1/Run2024I-MINIv6NANOv15-v1/NANOAOD
    run2024I_Muon:
      - /Muon0/Run2024I-MINIv6NANOv15-v1/NANOAOD
      - /Muon1/Run2024I-MINIv6NANOv15-v1/NANOAOD
    run2024I_MuonEG:
      - /MuonEG/Run2024I-MINIv6NANOv15-v2/NANOAOD
    run2024I_Tau:
      - /Tau/Run2024I-MINIv6NANOv15_v2-v1/NANOAOD

MC:
  VBFH-HTo2Tau:
    2024:
      - /VBFH-HTo2Tau_Par-M-125_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  # # DYto2L-2Jets_0J_M50_PT* Missing
  # DYto2L-2Jets_1J_M50_PT40to100:
  #   2024:
  #     - /DYto2L-2Jets_Bin-1J-MLL-50-PTLL-40to100_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/NANOAODSIM
  # DYto2L-2Jets_1J_M50_PT100to200:
  #   2024:
  #     - /DYto2L-2Jets_Bin-1J-MLL-50-PTLL-100to200_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  # DYto2L-2Jets_1J_M50_PT200to400:
  #   2024:
  #     - /DYto2L-2Jets_Bin-1J-MLL-50-PTLL-200to400_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  # DYto2L-2Jets_1J_M50_PT400to600:
  #   2024:
  #     - /DYto2L-2Jets_Bin-1J-MLL-50-PTLL-400to600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  # DYto2L-2Jets_1J_M50_PT600:
  #   2024:
  #     - /DYto2L-2Jets_Bin-1J-MLL-50-PTLL-600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  # DYto2L-2Jets_2J_M50_PT40to100:
  #   2024:
  #     - /DYto2L-2Jets_Bin-2J-MLL-50-PTLL-40to100_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/NANOAODSIM
  # DYto2L-2Jets_2J_M50_PT100to200:
  #   2024:
  #     - /DYto2L-2Jets_Bin-2J-MLL-50-PTLL-100to200_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  # DYto2L-2Jets_2J_M50_PT200to400:
  #   2024:
  #     - /DYto2L-2Jets_Bin-2J-MLL-50-PTLL-200to400_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  # DYto2L-2Jets_2J_M50_PT400to600:
  #   2024:
  #     - /DYto2L-2Jets_Bin-2J-MLL-50-PTLL-400to600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  # DYto2L-2Jets_2J_M50_PT600:
  #   2024:
  #     - /DYto2L-2Jets_Bin-2J-MLL-50-PTLL-600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  # add DYto2E and DYto2Mu with M10to50
  DYto2Tau-2Jets_0J_M50:
    2024:
      - /DYto2Tau-2Jets_Bin-0J-MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v4/NANOAODSIM
  DYto2Tau-2Jets_1J_M50:
    2024:
      - /DYto2Tau-2Jets_Bin-1J-MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  DYto2Tau-2Jets_2J_M50:
    2024:
      - /DYto2Tau-2Jets_Bin-2J-MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  # DYto2Tau-2Jets_M50: # I think this is inclusive DYto2Tau-2Jets not sure if needed
  #   2024:
  #     - /DYto2Tau-2Jets_Bin-MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v7/NANOAODSIM
  TTto2L2Nu:
    2024:
      - /TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/NANOAODSIM
  TTtoLNu2Q:
    2024:
      - /TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  TTto4Q:
    2024:
      - /TTto4Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  TWminusto2L2Nu:
    2024:
      - /TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  TWminustoLNu2Q:
    2024:
      - /TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  TWminusto4Q:
    2024:
      - /TWminusto4Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  TbarWplusto2L2Nu:
    2024:
      - /TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  TbarWplustoLNu2Q:
    2024:
      - /TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  TbarWplusto4Q:
    2024:
      - /TbarWplusto4Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WtoLNu-2Jets_PT600:
    2024:
      - /WtoLNu-2Jets_Bin-PTLNu-600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-JMENanoV15_150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WtoLNu-2Jets_1J_PT40to100:
    2024:
      - /WtoLNu-2Jets_Bin-1J-PTLNu-40to100_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/NANOAODSIM
  WtoLNu-2Jets_1J_PT100to200:
    2024:
      - /WtoLNu-2Jets_Bin-1J-PTLNu-100to200_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/NANOAODSIM
  WtoLNu-2Jets_1J_PT200to400:
    2024:
      - /WtoLNu-2Jets_Bin-1J-PTLNu-200to400_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WtoLNu-2Jets_1J_PT400to600:
    2024:
      - /WtoLNu-2Jets_Bin-1J-PTLNu-400to600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WtoLNu-2Jets_1J_PT600:
    2024:
      - /WtoLNu-2Jets_Bin-1J-PTLNu-600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WtoLNu-2Jets_2J_PT40to100:
    2024:
      - /WtoLNu-2Jets_Bin-2J-PTLNu-40to100_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/NANOAODSIM
  WtoLNu-2Jets_2J_PT100to200:
    2024:
      - /WtoLNu-2Jets_Bin-2J-PTLNu-100to200_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/NANOAODSIM
  WtoLNu-2Jets_2J_PT200to400:
    2024:
      - /WtoLNu-2Jets_Bin-2J-PTLNu-200to400_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WtoLNu-2Jets_2J_PT400to600:
    2024:
      - /WtoLNu-2Jets_Bin-2J-PTLNu-400to600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WtoLNu-2Jets_2J_PT600:
    2024:
      - /WtoLNu-2Jets_Bin-2J-PTLNu-600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WtoLNu-4Jets_1J:
    2024:
      - /WtoLNu-4Jets_Bin-1J_TuneCP5_13p6TeV_madgraphMLM-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WtoLNu-4Jets_2J:
    2024:
      - /WtoLNu-4Jets_Bin-2J_TuneCP5_13p6TeV_madgraphMLM-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WtoLNu-4Jets_3J:
    2024:
      - /WtoLNu-4Jets_Bin-3J_TuneCP5_13p6TeV_madgraphMLM-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WtoLNu-4Jets_4J:
    2024:
      - /WtoLNu-4Jets_Bin-4J_TuneCP5_13p6TeV_madgraphMLM-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WW:
    2024:
      - /WW_TuneCP5_13p6TeV_pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  WZ:
    2024:
      - /WZ_TuneCP5_13p6TeV_pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
  ZZ:
    2024:
      - /ZZ_TuneCP5_13p6TeV_pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM